# Generated by Django 5.2.3 on 2025-06-30 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.CharField(blank=True, max_length=24),
        ),
    ]
