# Generated by Django 5.2.3 on 2025-07-01 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0005_rename_book_id_book_isbn'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('#0', 'rented'), ('#1', 'returned'), ('#0', 'lost'), ('#0', 'delayed')], max_length=2)),
                ('rent_start_date', models.DateField(help_text='Date when book was rented')),
                ('rent_end_date', models.DateField(blank=True, help_text='Deadline to return')),
                ('return_date', models.DateField(blank=True, help_text='When book was actually returned')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
        ),
    ]
