# Generated by Django 5.2.3 on 2025-07-10 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_alter_rental_return_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rental',
            options={'ordering': ('-created',)},
        ),
    ]
