# Generated by Django 5.2.3 on 2025-07-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='book_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of currently rented books by this customer'),
        ),
    ]
