# Generated by Django 5.2.3 on 2025-07-09 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_rename_book_id_book_isbn'),
        ('publishers', '0002_alter_pubisher_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pubisher',
            new_name='Publisher',
        ),
    ]
